/* soapClient.c
   Generated by gSOAP 2.8.37 for SynchronizedAnaData.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.37 2016-11-05 07:27:00 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__synchronizedAnaData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_gateId, char *_equipId, char *_data, char *_equipIp, char *_equipDk, enum xsd__boolean *_synchronizedAnaDataReturn)
{	struct ns1__synchronizedAnaData soap_tmp_ns1__synchronizedAnaData;
	struct ns1__synchronizedAnaDataResponse *soap_tmp_ns1__synchronizedAnaDataResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1:8080/xcwlwWebService/services/SynchronizedAnaData";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp_ns1__synchronizedAnaData._gateId = _gateId;
	soap_tmp_ns1__synchronizedAnaData._equipId = _equipId;
	soap_tmp_ns1__synchronizedAnaData._data = _data;
	soap_tmp_ns1__synchronizedAnaData._equipIp = _equipIp;
	soap_tmp_ns1__synchronizedAnaData._equipDk = _equipDk;
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_serializeheader(soap);
	soap_serialize_ns1__synchronizedAnaData(soap, &soap_tmp_ns1__synchronizedAnaData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__synchronizedAnaData(soap, &soap_tmp_ns1__synchronizedAnaData, "ns1:synchronizedAnaData", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__synchronizedAnaData(soap, &soap_tmp_ns1__synchronizedAnaData, "ns1:synchronizedAnaData", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!_synchronizedAnaDataReturn)
		return soap_closesock(soap);
	soap_default_xsd__boolean(soap, _synchronizedAnaDataReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__synchronizedAnaDataResponse = soap_get_ns1__synchronizedAnaDataResponse(soap, NULL, "", NULL);
	if (!soap_tmp_ns1__synchronizedAnaDataResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (_synchronizedAnaDataReturn && soap_tmp_ns1__synchronizedAnaDataResponse->_synchronizedAnaDataReturn)
		*_synchronizedAnaDataReturn = *soap_tmp_ns1__synchronizedAnaDataResponse->_synchronizedAnaDataReturn;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
