// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* SynchronizedAnaData.h
   Generated by wsdl2h 2.8.37 from SynchronizedAnaData.xml and typemap.dat
   2016-11-05 07:26:27 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on SynchronizedAnaData.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stl.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://127.0.0.1:8080/xcwlwWebService/services/SynchronizedAnaData       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/

/// Built-in XSD type "SOAP-ENC:string".
typedef char* SOAP_ENC__string;

/// Built-in XSD type "xs:boolean".
enum xsd__boolean { xsd__boolean__false_, xsd__boolean__true_ };


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	SynchronizedAnaDataSoapBinding 
//gsoap ns1  service type:	SynchronizedAnaData 
//gsoap ns1  service port:	http://127.0.0.1:8080/xcwlwWebService/services/SynchronizedAnaData 
//gsoap ns1  service namespace:	http://bjxch.synch.com 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref SynchronizedAnaDataSoapBinding

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page SynchronizedAnaDataSoapBinding Binding "SynchronizedAnaDataSoapBinding"

@section SynchronizedAnaDataSoapBinding_operations Operations of Binding "SynchronizedAnaDataSoapBinding"

  - @ref ns1__synchronizedAnaData

@section SynchronizedAnaDataSoapBinding_ports Default endpoints of Binding "SynchronizedAnaDataSoapBinding"

  - http://127.0.0.1:8080/xcwlwWebService/services/SynchronizedAnaData

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   SynchronizedAnaDataSoapBinding                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns1__synchronizedAnaData                                                 *
 *                                                                            *
\******************************************************************************/


/** Operation "ns1__synchronizedAnaData" of service binding "SynchronizedAnaDataSoapBinding".

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Default endpoints:
    - http://127.0.0.1:8080/xcwlwWebService/services/SynchronizedAnaData

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns1__synchronizedAnaData(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    SOAP_ENC__string                    gateId,
    SOAP_ENC__string                    equipId,
    SOAP_ENC__string                    data,
    SOAP_ENC__string                    equipIp,
    SOAP_ENC__string                    equipDk,
    // output parameters:
    enum xsd__boolean                  *_synchronizedAnaDataReturn
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns1__synchronizedAnaData(
    struct soap *soap,
    // input parameters:
    SOAP_ENC__string                    gateId,
    SOAP_ENC__string                    equipId,
    SOAP_ENC__string                    data,
    SOAP_ENC__string                    equipIp,
    SOAP_ENC__string                    equipDk,
    // output parameters:
    enum xsd__boolean                  *_synchronizedAnaDataReturn
  );
@endcode

*/

//gsoap ns1  service method-protocol:	synchronizedAnaData SOAP
//gsoap ns1  service method-style:	synchronizedAnaData rpc
//gsoap ns1  service method-encoding:	synchronizedAnaData http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns1  service method-action:	synchronizedAnaData ""
//gsoap ns1  service method-output-action:	synchronizedAnaData Response
int ns1__synchronizedAnaData(
    SOAP_ENC__string                    :_gateId,	///< Input parameter, : unqualified name as per RPC encoding, _ wildcard name as per RPC parameterOrder
    SOAP_ENC__string                    :_equipId,	///< Input parameter, : unqualified name as per RPC encoding, _ wildcard name as per RPC parameterOrder
    SOAP_ENC__string                    :_data,	///< Input parameter, : unqualified name as per RPC encoding, _ wildcard name as per RPC parameterOrder
    SOAP_ENC__string                    :_equipIp,	///< Input parameter, : unqualified name as per RPC encoding, _ wildcard name as per RPC parameterOrder
    SOAP_ENC__string                    :_equipDk,	///< Input parameter, : unqualified name as per RPC encoding, _ wildcard name as per RPC parameterOrder
    enum xsd__boolean                  *:_synchronizedAnaDataReturn	///< Output parameter, : unqualified name as per RPC encoding, _ wildcard name as per RPC parameterOrder
);

/**

@page SynchronizedAnaDataSoapBinding Binding "SynchronizedAnaDataSoapBinding"

@section SynchronizedAnaDataSoapBinding_policy_enablers Policy Enablers of Binding "SynchronizedAnaDataSoapBinding"

None specified.

*/

/* End of SynchronizedAnaData.h */
